"""Initial baseline

Revision ID: bd0f7cf88e22
Revises: 
Create Date: 2026-05-02 19:13:19.009422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd0f7cf88e22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patient_profiles_patient_identifier', table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.create_foreign_key(None, 'anemia_assessments', 'visits', ['visit_id'], ['id'])
    op.alter_column('appointments', 'rescheduled_by',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('appointments', 'cancelled_by',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index('uq_appt_active_slot', 'appointments', ['doctor_id', 'appointment_date', 'start_time'], unique=True, postgresql_where=sa.text("status IN ('booked', 'pending_approval')"))
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('auth_users_email_key', 'auth_users', type_='unique')
    op.drop_index('idx_auth_users_email', table_name='auth_users')
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.drop_index('ix_dse_doctor_date', table_name='doctor_schedule_exceptions')
    op.drop_index('uq_dse_blocked', table_name='doctor_schedule_exceptions', postgresql_where="((kind)::text = 'blocked'::text)")
    op.create_foreign_key(None, 'fetal_health_assessments', 'visits', ['visit_id'], ['id'])
    op.create_foreign_key(None, 'gdm_assessments', 'visits', ['visit_id'], ['id'])
    op.add_column('patient_latest_assessments', sa.Column('percentage_of_time_with_abnormal_long_term_variability_updated_at', sa.DateTime(), nullable=True))
    op.alter_column('patient_latest_assessments', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('patient_latest_assessments', 'percentage_of_time_with_abnormal_long_term_variability_updated_')
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'contact_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'clinical_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('patients', 'risk_level',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.drop_constraint('fk_patients_doctor', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'auth_users', ['doctor_id'], ['id'])
    op.alter_column('visits', 'recorded_by_role',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_visits_recorded_by_user_id'), 'visits', ['recorded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_recorded_by_user_id'), table_name='visits')
    op.alter_column('visits', 'recorded_by_role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('fk_patients_doctor', 'patients', 'auth_users', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('patients', 'risk_level',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('patients', 'clinical_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'contact_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('patient_latest_assessments', sa.Column('percentage_of_time_with_abnormal_long_term_variability_updated_', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('patient_latest_assessments', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('patient_latest_assessments', 'percentage_of_time_with_abnormal_long_term_variability_updated_at')
    op.drop_constraint(None, 'gdm_assessments', type_='foreignkey')
    op.drop_constraint(None, 'fetal_health_assessments', type_='foreignkey')
    op.create_index('uq_dse_blocked', 'doctor_schedule_exceptions', ['doctor_id', 'exception_date'], unique=True, postgresql_where="((kind)::text = 'blocked'::text)")
    op.create_index('ix_dse_doctor_date', 'doctor_schedule_exceptions', ['doctor_id', 'exception_date'], unique=False)
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.create_index('idx_auth_users_email', 'auth_users', ['email'], unique=False)
    op.create_unique_constraint('auth_users_email_key', 'auth_users', ['email'])
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('uq_appt_active_slot', table_name='appointments', postgresql_where=sa.text("status IN ('booked', 'pending_approval')"))
    op.alter_column('appointments', 'cancelled_by',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('appointments', 'rescheduled_by',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'anemia_assessments', type_='foreignkey')
    op.create_table('patient_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_identifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doctor_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_report', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_identifier'], ['patients.patient_identifier'], name='patient_profiles_patient_identifier_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_profiles_pkey')
    )
    op.create_index('ix_patient_profiles_patient_identifier', 'patient_profiles', ['patient_identifier'], unique=True)
    # ### end Alembic commands ###
