import { useState, useEffect } from "react";
import { Plus, Search, Users, AlertCircle, Sparkles } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { PatientCard } from "@/components/PatientCard";
import { AddPatientModal } from "@/components/AddPatientModal";
import { useAuth } from "@/context/AuthContext";
import { apiFetch } from "@/lib/apiClient";

interface PatientProfile {
  id: number;
  patient_identifier: string;
  name: string;
  age: number;
  contact_number: string;
  clinical_notes: string | null;
  risk_level: 'unassessed' | 'high' | 'medium' | 'low';
  number_of_pregnancies: number | null;
  bmi_category: number | null;
  family_history: boolean | null;
  pcos: boolean | null;
  created_at: string;
  updated_at: string;
}

const API_URL = "http://localhost:8000";

const PatientsPage = () => {
  const { user, tokens, setTokens, logout } = useAuth();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [patients, setPatients] = useState<PatientProfile[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    if (user?.email) {
      fetchPatients();
    }
  }, [user?.email]);

  const fetchPatients = async () => {
    try {
      setLoading(true);
      const response = await apiFetch(
        `/api/patients/`,
        { method: "GET" },
        tokens,
        setTokens,
        logout,
      );

      if (!response.ok) {
        throw new Error('Failed to fetch patients');
      }

      const data: PatientProfile[] = await response.json();
      setPatients(data);
      setError(null);
    } catch (err) {
      console.error('Error fetching patients:', err);
      setError('Failed to load patients. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleAddPatient = async (newPatient: { name: string; age: string; phone: string }) => {
    try {
      // Create the patient with all required fields in a single POST request
      // patient_identifier will be auto-generated by the backend
      const patientResponse = await apiFetch(
        `/api/patients/`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            name: newPatient.name,
            age: parseInt(newPatient.age),
            contact_number: newPatient.phone,
            clinical_notes: null,
            number_of_pregnancies: null,
            bmi_category: null,
            family_history: null,
            pcos: null,
            unexplained_prenatal_loss: null,
            large_child_or_birth_default: null,
            prediabetes: null,
          }),
        },
        tokens,
        setTokens,
        logout,
      );

      if (!patientResponse.ok) {
        const errorData = await patientResponse.json();
        throw new Error(errorData.detail || 'Failed to create patient');
      }

      await fetchPatients(); // Refresh the list
      setIsModalOpen(false);
    } catch (err) {
      console.error('Error adding patient:', err);
      alert(`Failed to add patient: ${err instanceof Error ? err.message : 'Unknown error'}`);
    }
  };

  // Filter patients based on search query
  const filteredPatients = patients.filter(patient =>
    patient.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    patient.patient_identifier.toLowerCase().includes(searchQuery.toLowerCase())
  );

  // Skeleton Loader Component
  const SkeletonCard = () => (
    <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-md border border-gray-200/50 overflow-hidden animate-pulse">
      <div className="p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="w-16 h-16 rounded-full bg-gray-200" />
          <div className="w-20 h-6 rounded-full bg-gray-200" />
        </div>
        <div className="h-4 w-16 bg-gray-200 rounded mb-2" />
        <div className="h-6 w-32 bg-gray-200 rounded mb-4" />
        <div className="h-[2px] bg-gray-200 mb-4" />
        <div className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gray-200" />
            <div className="flex-1">
              <div className="h-3 w-12 bg-gray-200 rounded mb-1" />
              <div className="h-4 w-24 bg-gray-200 rounded" />
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gray-200" />
            <div className="flex-1">
              <div className="h-3 w-12 bg-gray-200 rounded mb-1" />
              <div className="h-4 w-32 bg-gray-200 rounded" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );

  // Loading state with skeleton loaders
  if (loading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <main className="container mx-auto px-4 sm:px-6 py-8 sm:py-10">
          <div className="mb-10">
            <div className="inline-block">
              <div className="h-10 w-64 bg-gray-200 rounded mb-3 animate-pulse" />
              <div className="h-1 w-32 bg-gradient-to-r from-medical-pink to-medical-blue rounded-full" />
            </div>
            <div className="h-6 w-96 bg-gray-200 rounded mt-3 animate-pulse" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 pt-4">
            {[...Array(8)].map((_, i) => (
              <SkeletonCard key={i} />
            ))}
          </div>
        </main>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <main className="container mx-auto px-4 sm:px-6 py-8 sm:py-10">
          <div className="max-w-md mx-auto text-center mt-20">
            <div className="w-20 h-20 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-6">
              <AlertCircle className="w-10 h-10 text-red-500" />
            </div>
            <h2 className="text-2xl font-bold text-gray-900 mb-3">Oops! Something went wrong</h2>
            <p className="text-gray-600 mb-6">{error}</p>
            <button
              onClick={fetchPatients}
              className="px-6 py-3 bg-gradient-to-r from-medical-pink to-medical-blue text-white font-semibold rounded-lg hover:shadow-xl hover:scale-105 transition-all duration-300"
            >
              Try Again
            </button>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto px-4 sm:px-6 py-8 sm:py-10">
        {/* Header Section */}
        <div className="mb-10 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
          <div>
            <div className="inline-block">
              <h2 className="text-3xl sm:text-4xl font-bold bg-gradient-to-r from-medical-pink via-medical-blue to-medical-pink bg-clip-text text-transparent mb-3 animate-float">
                All Patients
              </h2>
              <div className="h-1 w-32 bg-gradient-to-r from-medical-pink to-medical-blue rounded-full" />
            </div>
            <p className="text-muted-foreground mt-3 text-lg">
              Manage and monitor patient information and risk levels
            </p>

            {/* Patient Count Badge */}
            <div className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-medical-blue/10 to-medical-pink/10 rounded-full border border-medical-blue/20">
              <Users className="w-4 h-4 text-medical-blue" />
              <span className="text-sm font-semibold text-gray-700">
                {patients.length} {patients.length === 1 ? 'Patient' : 'Patients'}
              </span>
            </div>
          </div>

          <button
            onClick={() => setIsModalOpen(true)}
            className="group relative px-6 py-3 bg-gradient-to-r from-medical-pink to-medical-blue text-white font-semibold rounded-lg shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105 flex items-center gap-2"
          >
            <Plus className="w-5 h-5" />
            Add New Patient
            <div className="absolute inset-0 rounded-lg bg-gradient-to-r from-medical-pink to-medical-blue opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300" />
          </button>
        </div>

        {/* Search Bar */}
        {patients.length > 0 && (
          <div className="mb-8 max-w-md">
            <div className="relative group">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400 group-focus-within:text-medical-blue transition-colors" />
              <input
                type="text"
                placeholder="Search patients by name or ID..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-12 pr-4 py-3 bg-white/80 backdrop-blur-sm border border-gray-200 rounded-xl focus:ring-2 focus:ring-medical-blue focus:border-transparent transition-all outline-none shadow-sm hover:shadow-md"
              />
            </div>
          </div>
        )}

        {/* Empty State */}
        {patients.length === 0 ? (
          <div className="text-center py-20">
            <div className="relative inline-block mb-8">
              {/* Animated background blobs */}
              <div className="absolute -inset-4 bg-gradient-to-r from-medical-pink/20 to-medical-blue/20 rounded-full blur-2xl animate-pulse" />
              <div className="relative w-32 h-32 bg-gradient-to-br from-medical-pink to-medical-blue rounded-full flex items-center justify-center shadow-2xl">
                <Users className="w-16 h-16 text-white" />
              </div>
            </div>

            <h3 className="text-2xl font-bold text-gray-900 mb-3">No patients yet</h3>
            <p className="text-gray-600 mb-8 max-w-md mx-auto">
              Start building your patient database by adding your first patient.
              Click the button above to get started!
            </p>

            <button
              onClick={() => setIsModalOpen(true)}
              className="group relative inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-medical-pink to-medical-blue text-white font-semibold rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 hover:scale-105"
            >
              <Sparkles className="w-5 h-5" />
              Add Your First Patient
              <div className="absolute inset-0 rounded-xl bg-white opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300" />
            </button>
          </div>
        ) : filteredPatients.length === 0 ? (
          // No search results
          <div className="text-center py-20">
            <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6">
              <Search className="w-10 h-10 text-gray-400" />
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-2">No patients found</h3>
            <p className="text-gray-600">
              Try adjusting your search query
            </p>
          </div>
        ) : (
          // Patient Grid with Staggered Animation
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 pt-4">
            {filteredPatients.map((patient, index) => (
              <div
                key={patient.patient_identifier}
                className="animate-in fade-in slide-in-from-bottom-4 duration-500"
                style={{ animationDelay: `${index * 50}ms` }}
              >
                <PatientCard
                  id={patient.patient_identifier}
                  name={patient.name}
                  age={patient.age.toString()}
                  contactNumber={patient.contact_number}
                  riskLevel={patient.risk_level}
                />
              </div>
            ))}
          </div>
        )}
      </main>

      <AddPatientModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onAdd={handleAddPatient}
      />
    </div>
  );
};

export default PatientsPage;
